---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: bosh-errand
  type: docker-image
  source:
    repository: pcfkubo/bosh2-errand-resource
    tag: v0.1.3-dev

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master

- name: git-kubo-release
  type: pull-request
  source:
    repository: cloudfoundry-incubator/kubo-release
    access_token: ((github-token-key))

- name: gcs-pr-release-tarball
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: release-pr/kubo-release.tgz

- name: kubo-version
  type: semver
  source:
    key: versions/kubo-version
    access_key_id: ((gcs-access-key-id))
    secret_access_key: ((gcs-secret-access-key))
    bucket: kubo-pipeline-store
    region_name: us-east1
    endpoint: storage.googleapis.com

jobs:
- name: run-unit-tests
  plan:
  - get: git-kubo-ci
  - get: git-kubo-release
    version: every
  - put: git-kubo-release
    params:
      path: git-kubo-release
      status: pending
  - task: run-unit-tests
    file: git-kubo-ci/tasks/run-release-unit-tests.yml
    on_failure: &on_failure
      put: git-kubo-release
      params:
        path: git-kubo-release
        status: failure

- name: build-kubo-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-version
    - get: git-kubo-release
      passed: [ 'run-unit-tests' ]
      trigger: true
  - put: git-kubo-release
    params:
      path: git-kubo-release
      status: pending
  - task: build-kubo-release
    file: git-kubo-ci/tasks/build-kubo-release.yml
    on_failure: *on_failure
  - put: gcs-pr-release-tarball
    params:
      file: kubo-release/kubo-release-*.tgz
