<%
  pools = %w(aws-lb gcp-lb openstack-lb openstack vsphere-lb vsphere-proxy)
%>

resource_types:
- name: pool-trigger
  type: docker-image
  source:
    repository: cfmobile/pool-trigger

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/kubo-ci
    branch: master

- name: gcp-lifecycle-trigger
  type: pool-trigger
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    pool: gcp-lifecycle
    private_key: ((git-ssh-key.private_key))

- name: gcp-lifecycle
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    private_key: ((git-ssh-key.private_key))
    pool: gcp-lifecycle

- name: gcp-pool
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    private_key: ((git-ssh-key.private_key))
    pool: gcp

<% pools.each do |pool| %>
- name: kubo-lock-<%= pool %>-lifecycle-trigger
  type: pool-trigger
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    pool: kubo-<%= pool %>-lifecycle
    private_key: ((git-ssh-key.private_key))

- name: kubo-lock-<%= pool %>-lifecycle
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    private_key: ((git-ssh-key.private_key))
    pool: kubo-<%= pool %>-lifecycle

- name: kubo-lock-<%= pool %>
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    private_key: ((git-ssh-key.private_key))
    pool: kubo-<%= pool %>
<% end %>

jobs:
<% pools.each do |pool| %>
<% env = pool.gsub(/-.*/, '') %>
- name: claim-lock-<%= pool %>
  plan:
  - get: kubo-lock-<%= pool %>-lifecycle-trigger
    trigger: true
    version: every
  - put: kubo-lock-<%= pool %>-lifecycle
    params: { acquire: true }
- name: cleanup-<%= pool %>
  plan:
  - aggregate:
    - get: kubo-lock-<%= pool %>-lifecycle
      version: every
      trigger: true
      passed: [ 'claim-lock-<%= pool %>' ]
    - get: git-kubo-ci
  - task: cleanup-<%= pool %>
    file: git-kubo-ci/tasks/cleanup-<%= env %>-environment.yml
    params: { ENV_FILE: 'kubo-lock/metadata' }
    tags:
    - <%= pool %>
    input_mapping:
      kubo-lock: kubo-lock-<%= pool %>-lifecycle
  - put: kubo-lock-<%= pool %>
    params: { add: kubo-lock-<%= pool %>-lifecycle }
  - put: kubo-lock-<%= pool %>-lifecycle
    params: { remove: kubo-lock-<%= pool %>-lifecycle }
<% end %>

- name: gcp-destroy-k8s
  plan:
  - get: gcp-lifecycle-trigger
    version: every
    trigger: true
  - aggregate:
    - put: gcp-lifecycle
      params:
        acquire: true
    - get: git-kubo-ci
  - task: destroy-k8s
    file: git-kubo-ci/tasks/destroy-k8s-instance-long-lived-director.yml
    input_mapping:
      kubo-lock: gcp-lifecycle
  - put: gcp-pool
    params: { add: gcp-lifecycle }
  - put: gcp-lifecycle
    params: { remove: gcp-lifecycle }
