resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: slack-alert
  type: slack-notification
  source:
    url: ((build-alert-slack-url))

- name: git-kubo-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-ci
    branch: master
    private_key: ((git-ssh-key.private_key))

<% arr = %w(gcp-pod-security-policy-integration azure-vanilla-integration gcp-custom-cidrs-integration gcp-vanilla-istio gcp-vanilla-turbulence) %> 
<% arr.each do |pipeline| %>
- name: gcs-<%= pipeline %>-shipables
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: shipables/<%= pipeline %>
<% end %>

jobs:
- name: signal-aggregator
  plan:
  - aggregate:
    - get: git-kubo-ci
    <% arr.each do |pipeline|%>
    - get: gcs-<%= pipeline %>-shipables
      trigger: true
      version: every
    <% end %>
  - task: aggregate-test-signals
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      params:
        SLACK_MESSAGE_FILE: "slack/message"
      outputs:
      - name: slack
      inputs:
      - name: git-kubo-ci
      <% arr.each do |pipeline| %>
      - name: gcs-<%= pipeline %>-shipables
      <% end %>
      run:
        path: git-kubo-ci/scripts/aggregate-test-signals.sh
  - put: slack-alert
    params:
      attachments_file: slack-notification/attachments
      text_file: "slack/message"


