resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-ci
    branch: master
    private_key: ((git-ssh-key.private_key))

- name: gcs-istio-shipables
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: shipables/istio

- name: gcs-bbr-shipables
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: shipables/bbr

- name: gcs-cidr-shipables
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: shipables/cidr

jobs:
- name: signal-aggregator
  plan:
  - get: git-kubo-ci
  - get: gcs-istio-shipables
  - get: gcs-bbr-shipables
  - get: gcs-cidr-shipables
  - task: aggregate-test-signals
    file: git-kubo-ci/tasks/aggregate-test-signals.yml

