resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: git-kubo-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-release.git
    branch: develop
    private_key: ((git-ssh-key.private_key))
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'

- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-deployment.git
    branch: wip-159895436-precompiled-releases
    private_key: ((git-ssh-key.private_key))
    ignore_paths:
    - 'LICENSE'
    - 'NOTICE'

- name: git-kubo-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-ci
    branch: wip-159895436-precompiled-releases
    private_key: ((git-ssh-key.private_key))

- name: gcs-kubo-release-tarball-untested
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    regexp: dev-builds/kubo-release-(.*).tgz

- name: gcs-precompiled-kubo-untested
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-precompiled-releases
    regexp: kubo-(.*).tgz

- name: gcs-precompiled-cfcr-etcd-untested
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-precompiled-releases
    regexp: cfcr-etcd-(.*).tgz

- name: gcs-precompiled-docker-untested
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-precompiled-releases
    regexp: docker-(.*).tgz

- name: gcs-precompiled-bpm-untested
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-precompiled-releases
    regexp: bpm-(.*).tgz

- name: compilation-deployment
  type: bosh-deployment
  source:
    deployment: compilation
    skip_check: true

- name: gaffer-director-creds
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: gaffer-env/creds.yml

- name: gaffer-director-metadata
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: gaffer-env/metadata # Named so because locks are called metadata

- name: kubo-version
  type: semver
  source:
    driver: gcs
    key: versions/kubo-version
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store

jobs:
- name: compile-releases
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: git-kubo-release
    - get: gcs-kubo-release-tarball-untested
    - get: gaffer-director-creds
    - get: gaffer-director-metadata
    - get: kubo-version
  - task: upload-stemcell
    tags: ['gaffer']
    file: git-kubo-ci/tasks/upload-stemcell.yml
    input_mapping:
      gcs-bosh-creds: gaffer-director-creds
      kubo-lock: gaffer-director-metadata
    params:
      IAAS: gcp
  - task: generate-compilation-manifest
    file: git-kubo-ci/tasks/generate-compilation-manifest.yml
    params:
      RELEASE_LIST: "docker cfcr-etcd kubo bpm"
  - task: generate-source-json
    file: git-kubo-ci/tasks/generate-source-json.yml
    input_mapping:
      gcs-bosh-creds: gaffer-director-creds
      kubo-lock: gaffer-director-metadata
  - put: compilation-deployment
    params:
      manifest: compilation-manifest/manifest.yml
      source_file: source-json/source.json
      releases:
      - gcs-kubo-release-tarball-untested/*.tgz
    tags: ['gaffer']
  - task: export
    tags: ['gaffer']
    file: git-kubo-ci/tasks/export-release.yml
    params:
      RELEASE_LIST: "docker cfcr-etcd kubo bpm"
  - aggregate:
    - put: gcs-precompiled-kubo-untested
      params:
        file: compiled-releases/kubo-*.tgz
    - put: gcs-precompiled-cfcr-etcd-untested
      params:
        file: compiled-releases/cfcr-etcd-*.tgz
    - put: gcs-precompiled-docker-untested
      params:
        file: compiled-releases/docker-*.tgz
    - put: gcs-precompiled-bpm-untested
      params:
        file: compiled-releases/bpm-*.tgz
  - task: bump-precompiled-releases-in-manifest
    file: git-kubo-ci/tasks/bump-precompiled-releases-in-manifest.yml
    params:
      RELEASE_LIST: "docker cfcr-etcd kubo bpm"
