resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: gcs-source-json
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: gaffer-env/source.json

- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-deployment.git
    branch: wip-159895436-precompiled-releases
    private_key: ((git-ssh-key.private_key))
    ignore_paths:
    - 'LICENSE'
    - 'NOTICE'

- name: git-kubo-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-ci
    private_key: ((git-ssh-key.private_key))

- name: gcs-precompiled-cfcr-etcd-untested
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-precompiled-releases
    regexp: cfcr-etcd-(.*).tgz

- name: gcs-precompiled-docker-untested
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-precompiled-releases
    regexp: docker-(.*).tgz

- name: gcs-precompiled-bpm-untested
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-precompiled-releases
    regexp: bpm-(.*).tgz

- name: compilation-deployment
  type: bosh-deployment
  source:
    deployment: compilation
    skip_check: true

jobs:
- name: compile-releases
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: gcs-source-json
  - task: upload-stemcell
    tags: ['gaffer']
    file: git-kubo-ci/tasks/upload-stemcell.yml
    params:
      IAAS: gcp
  - task: generate-compilation-manifest
    file: git-kubo-ci/tasks/generate-compilation-manifest.yml
    params:
      RELEASE_LIST: "docker cfcr-etcd bpm"
  - put: compilation-deployment
    params:
      manifest: compilation-manifest/manifest.yml
      source_file: gcs-source-json/source.json
    tags: ['gaffer']
  - task: export
    tags: ['gaffer']
    file: git-kubo-ci/tasks/export-release.yml
    params:
      RELEASE_LIST: "docker cfcr-etcd bpm"
  - aggregate:
    - put: gcs-precompiled-cfcr-etcd-untested
      params:
        file: compiled-releases/cfcr-etcd-*.tgz
    - put: gcs-precompiled-docker-untested
      params:
        file: compiled-releases/docker-*.tgz
    - put: gcs-precompiled-bpm-untested
      params:
        file: compiled-releases/bpm-*.tgz
  - task: bump-precompiled-releases-in-manifest
    file: git-kubo-ci/tasks/bump-precompiled-releases-in-manifest.yml
    params:
      RELEASE_LIST: "docker cfcr-etcd bpm"
