---
releases:
- name: "turbulence"
  version: "0.10.0"
  url: "https://bosh.io/d/github.com/cppforlife/turbulence-release?v=0.10.0"
  sha1: "259344312796e23500b2836a15140f8f09ad99ee"

addons:
- name: turbulence_agent
  jobs:
  - name: turbulence_agent
    release: turbulence
    consumes:
      api:
        instances:
        - address: ((internal_ip))
        properties:
          advertised_host: ""
          username: turbulence
          password: ((turbulence_api_password))
          agent_listen_port: 8081
          cert:
            ca: ((turbulence_api_ssl.ca))
