platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
- name: git-kubo-ci
- name: gcs-gcp-vanilla-turbulence-shipables
- name: gcs-gcp-custom-cidrs-integration-shipables
- name: gcs-gcp-vanilla-istio-shipables

run:
  path: git-kubo-ci/scripts/aggregate-test-signals.sh
