platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
- name: gcs-istio-shipables
- name: gcs-bbr-shipables
- name: gcs-cidr-shipables

params:
  SHIPABLE_SIGNALS: "istio cidr bbr"

run:
  path: git-kubo-ci/scripts/aggregate-test-signals.sh
