platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/run-k8s-turbulence-tests.sh

params:
  DEPLOYMENT_NAME:
  ENABLE_TURBULENCE_WORKER_DRAIN_TESTS:
  ENABLE_TURBULENCE_WORKER_FAILURE_TESTS:
  ENABLE_TURBULENCE_MASTER_FAILURE_TESTS:
  ENABLE_TURBULENCE_PERSISTENCE_FAILURE_TESTS:
  KUBECONFIG_FILE: config
  IAAS:

inputs:
  - name: git-kubo-ci
  - name: gcs-kubeconfig
  - name: gcs-bosh-creds
    optional: true
  - name: kubo-lock
  - name: git-kubo-deployment
  - name: source-json
    optional: true
