platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: /bin/bash
  args:
  - -exc
  - |
    tar -xzf  gcs-kubo-deployment-pre/kubo-deployment*.tgz -C git-kubo-deployment/
    mv git-kubo-deployment/kubo-deployment*/* git-kubo-deployment/
inputs:
- name: gcs-kubo-deployment-pre
outputs:
- name: git-kubo-deployment
