platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/dind-kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/bump-k8s-spec.sh

params:
  ACCESS_KEY_ID:
  SECRET_ACCESS_KEY:

inputs:
- name: git-kubo-ci
- name: git-kubo-release
- name: coredns-release
- name: metrics-server-release
- name: kubernetes-dashboard-release
- name: spec-to-update

outputs:
- name: git-kubo-release-output
