platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/compare-specs.sh

inputs:
- name: git-kubo-ci
- name: git-kubo-release
- name: coredns-release
- name: kubernetes-dashboard-release
- name: metrics-server-release

outputs:
- name: spec-to-update
