vm_types:
- name: concourse-worker
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 200
    root_disk_type: pd-ssd
    service_account: gaffer-kubo@cf-pcf-kubo.iam.gserviceaccount.com
    tags:
    - no-ip
    - internal
