instance_groups:
- azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: postgres
    release: postgres
  lifecycle: service
  name: db
  networks:
  - name: default
  persistent_disk_type: large
  properties:
    databases:
      port: 5432
      databases:
      - name: atc
      roles:
      - name: atc
        password: ((postgresql-password))
  stemcell: default
  update:
    max_in_flight: 1
  vm_type: default
- azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: atc
    properties:
      token_signing_key: ((token-signing-key))
      main_team:
        auth:
          github:
            teams:
            - pivotal-cf-experimental:pcf-kubo
            - cloudfoundry-incubator:cfcr
            - "cloudfoundry-incubator:CFCR Core"
            - pivotal-cf:vmware-kubo
            - pivotal-cf:pks-releng
            users:
            - lamlouis
            - astrieanna
            - benmoss
      github_auth:
        client_id: ((github-client-id))
        client_secret: ((github-client-secret))
      external_url: https://ci.kubo.sh
      tls_cert: ((atc-certificate.certificate))((atc-certificate.ca))
      tls_key: ((atc-certificate.private_key))
      tls_bind_port: 443
      bind_port: 80
      postgresql:
        database: atc
        role:
          name: atc
          password: ((postgresql-password))
      credhub:
        url: https://10.1.0.2:8844
        tls:
          insecure_skip_verify: true
        client_id: director_to_credhub
        client_secret: ((uaa_clients_director_to_credhub))
    release: concourse
  - name: tsa
    properties:
      token_signing_key: ((token-signing-key))
      host_key: ((tsa-host-key))
      host_public_key: ((tsa-host-key.public_key))
      authorized_keys:
      - ((worker-key.public_key))
    release: concourse
  lifecycle: service
  name: concourse
  networks:
  - default:
    - dns
    - gateway
    name: default
  persistent_disk_type: large
  properties: {}
  stemcell: default
  update:
    max_in_flight: 1
  vm_type: default
  vm_extensions:
  - gcp-lb
- azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: worker
    release: concourse
    consumes:
      baggageclaim: {from: bc-gcp}
    properties:
      tags:
        - gcp
        - gcp-lb
      tsa:
        worker_key: ((worker-key))
        host_public_key: ((tsa-host-key.public_key))
  - name: baggageclaim
    release: concourse
    provides:
      baggageclaim: {as: bc-gcp}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_address: 0.0.0.0:7777
        listen_network: tcp
  lifecycle: service
  name: worker-gcp
  networks:
  - name: default
  stemcell: default
  update:
    max_in_flight: 1
  vm_type: large
- azs: [z1, z2, z3]
  instances: 5
  jobs:
  - name: worker
    release: concourse
    consumes:
      baggageclaim: {from: bc}
    properties:
      tsa:
        worker_key: ((worker-key))
        host_public_key: ((tsa-host-key.public_key))
  - name: baggageclaim
    release: concourse
    provides:
      baggageclaim: {as: bc}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_address: 0.0.0.0:7777
        listen_network: tcp
  lifecycle: service
  name: worker
  networks:
  - name: default
  stemcell: default
  update:
    max_in_flight: 1
  vm_type: large
name: kubo-ci
releases:
- name: concourse
  sha1: 470a6fdd7cb82fc723d7d78930c7d261ca4a6cb4
  url: https://bosh.io/d/github.com/concourse/concourse?v=4.2.1
  version: 4.2.1
- name: garden-runc
  sha1: 2a7c813e7e4d862e19334addf022916fb6b91eb0
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.16.3
  version: 1.16.3
- name: postgres
  version: 30
  sha1: a798999d29b9f5aa12035cff907b26674b491200
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=30
stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
update:
  canaries: 1
  canary_watch_time: 30000-300000
  max_errors: 2
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-300000

variables:
- name: kubo_admin_password
  type: password
- name: postgresql-password
  type: password
- name: token-signing-key
  type: rsa
